run:
  skip-dirs:
  skip-files:

linters-settings:
  lll:
    line-length: 120

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - staticcheck
    - unconvert
    - unused
